---
title: "12_DataVisualization.rmd"
output: html_document
date: "2025-03-13"
---
```{r}
source("00_requirements.R")
source("02_func_dVisual_PlotDensity.R")
df <- read.csv("cleaned_sleep_health_data.csv")
```



```{r}
# 1. sleep quality of sleep apnea vs sleep quality of insomnia
t_test_result1 <- t.test(df$sleep_quality[df$disorder == "Sleep Apnea"],
       df$sleep_quality[df$disorder == "Insomnia"])
plot_density(df,"sleep_quality", "Sleep Apnea", "Insomnia", "Figure1: Sleep Quality: Sleep Apnea vs. Insomnia")
t_test_result1
# p value: 0.001583
# means: 7.205128  6.532468 
```

```{r}
# 2. the stress level with the ppl with sleep apnea vs thestress level with the ppl with insomnia \
t_test_result2 <- t.test(df$stress[df$disorder == "Sleep Apnea"],
       df$stress[df$disorder == "Insomnia"])
plot_density(df, "stress", "Sleep Apnea", "Insomnia", "Figure2: Stress Level: Sleep Apnea vs. Insomnia")
t_test_result2
# p value: 0.5161
# means: 5.666667  5.870130 
```

```{r}
# 3. the quality of sleeping with the ppl without sleeping disorder vs the quality of sleeping with the ppl with insomnia 

t_test_result3 <- t.test(df$sleep_quality[df$disorder == "None"],
       df$sleep_quality[df$disorder == "Insomnia"])
plot_density(df, "sleep_quality", "None", "Insomnia", "Figure3: Sleep Quality: No Disorder vs. Insomnia")
t_test_result3
# p value: 
# means:
```

```{r}
# 4. the quality of sleeping with the ppl without sleeping disorder vs the quality of sleeping with the ppl with sleep apnea
t_test_result4 <- t.test(df$sleep_quality[df$disorder == "None"],
       df$sleep_quality[df$disorder == "Sleep Apnea"])
plot_density(df, "sleep_quality", "None", "Sleep Apnea", "Figure4: Sleep Quality: No Disorder vs. Sleep Apnea")
t_test_result4
# p value: 
# means:
```

```{r}
# 5. the stress level with the ppl without sleeping disorder vs the stress levelwith the ppl with insomnia 
t_test_result5 <- t.test(df$stress[df$disorder == "None"],
       df$stress[df$disorder == "Insomnia"])
plot_density(df, "stress", "None", "Insomnia", "Figure5: Stress Level: No Disorder vs. Insomnia")
t_test_result5
# p value: 
# means:
```

```{r}
# 6. the stress level with the ppl without sleeping disorder vs the stress levelwith the ppl with sleep apnea. 
t_test_result6 <- t.test(df$stress[df$disorder == "None"],
       df$stress[df$disorder == "Sleep Apnea"])
plot_density(df, "stress", "None", "Sleep Apnea", "Figure6: Stress Level: No Disorder vs. Sleep Apnea")
t_test_result6
# p value: 
# means:
```